---
- src: clusterapps.freeipa_client
  name: freeipa_client
- src: clusterapps.httpd
  name: httpd
- src: bertvv.mariadb
  name: mariadb
- src: clusterapps.rhbase
  name: rhbase  
- src: clusterapps.wordpress
  name: wordpress
- src: sean797.foreman_installer
  name: foreman_installer  
- src: clusterapps.freeipa_server
  name: freeipa_server
- src: mrlesmithjr.windows-updates
  name: win_updates
- src: arillso.chocolatey
  name: win_choco

