- name: Install | Kubernetes dependencies
  hosts: kubernetes
  tasks:
    - name: Disable firewalld
      service:
        name: firewalld
        enabled: false
        state: stopped
  roles:
    - rhbase
    - pip
    - docker

- name: Reboot to set SELinux and firewalld
  hosts: kubernetes
  tasks:
    - name: Unconditionally reboot the machine with new defaults
      reboot:

- name: Deploy Kubernetes Master
  hosts: k8s-master
  vars:
    - kubernetes_role: "master"
  roles:
    - kubernetes

- name: Deploy Kubernetes Nodes
  hosts: k8s-node
  vars:
    - kubernetes_role: "node"
  roles:
    - kubernetes    