- name: Install | Foreman dependencies
  hosts: kubernetes
  tasks:
    - name: Disable firewalld
      service:
        name: firewalld
        enabled: false
        state: stopped

- name: Deploy Kubernetes Master
  hosts: k8s-master
  roles:
    - rhbase
    - pip
    - docker
    - kubernetes

- name: Deploy Kubernetes Nodes
  hosts: k8s-node
  vars:
    - kubernetes_role: "node"
  roles:
    - rhbase
    - pip
    - docker
    - kubernetes    