- name: Check oVirt Repo settings
  hosts: ovirt
  roles:
    - rhbase
    - freeipa_client
    - ovirt.repositories
    
# - name: Configure oVirt Database
#   hosts: ovirt-db
#   roles:
#     - ovirt.remote_db

- name: Configure oVirt Engine
  hosts: ovirt-engine
  roles:
    - ovirt.engine-setup