---
- name: Install | Foreman dependencies
  hosts: katello
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ katello_dependencies }}"

- hosts:
  - katello
  roles:
    - role: foreman_installer