---
- name: Install | Foreman dependencies
  hosts: katello
  tasks:
    - name: Add repo
      package:
        name: "{{ item }}"
        state: installed
      with_items: "{{ katello_dependencies }}"

- name: Deploy Katello
  hosts: katello
  roles:
    - foreman_installer